/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelfieRouteImport } from './routes/selfie'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ApiEnhanceRouteImport } from './routes/api/enhance'
import { Route as ApiVideoRouteImport } from './routes/api/video'
import { Route as ExperienceSceneRouteImport } from './routes/experience.$scene'
import { Route as RTokenRouteImport } from './routes/r.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfieRoute = SelfieRouteImport.update({
  id: '/selfie',
  path: '/selfie',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnhanceRoute = ApiEnhanceRouteImport.update({
  id: '/api/enhance',
  path: '/api/enhance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoRoute = ApiVideoRouteImport.update({
  id: '/api/video',
  path: '/api/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceSceneRoute = ExperienceSceneRouteImport.update({
  id: '/experience/$scene',
  path: '/experience/$scene',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/selfie': typeof SelfieRoute
  '/world': typeof WorldRoute
  '/api/enhance': typeof ApiEnhanceRoute
  '/api/video': typeof ApiVideoRoute
  '/experience/$scene': typeof ExperienceSceneRoute
  '/r/$token': typeof RTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/selfie': typeof SelfieRoute
  '/world': typeof WorldRoute
  '/api/enhance': typeof ApiEnhanceRoute
  '/api/video': typeof ApiVideoRoute
  '/experience/$scene': typeof ExperienceSceneRoute
  '/r/$token': typeof RTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/selfie': typeof SelfieRoute
  '/world': typeof WorldRoute
  '/api/enhance': typeof ApiEnhanceRoute
  '/api/video': typeof ApiVideoRoute
  '/experience/$scene': typeof ExperienceSceneRoute
  '/r/$token': typeof RTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/selfie'
    | '/world'
    | '/api/enhance'
    | '/api/video'
    | '/experience/$scene'
    | '/r/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/selfie'
    | '/world'
    | '/api/enhance'
    | '/api/video'
    | '/experience/$scene'
    | '/r/$token'
  id:
    | '__root__'
    | '/'
    | '/selfie'
    | '/world'
    | '/api/enhance'
    | '/api/video'
    | '/experience/$scene'
    | '/r/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelfieRoute: typeof SelfieRoute
  WorldRoute: typeof WorldRoute
  ApiEnhanceRoute: typeof ApiEnhanceRoute
  ApiVideoRoute: typeof ApiVideoRoute
  ExperienceSceneRoute: typeof ExperienceSceneRoute
  RTokenRoute: typeof RTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selfie': {
      id: '/selfie'
      path: '/selfie'
      fullPath: '/selfie'
      preLoaderRoute: typeof SelfieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enhance': {
      id: '/api/enhance'
      path: '/api/enhance'
      fullPath: '/api/enhance'
      preLoaderRoute: typeof ApiEnhanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video': {
      id: '/api/video'
      path: '/api/video'
      fullPath: '/api/video'
      preLoaderRoute: typeof ApiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$scene': {
      id: '/experience/$scene'
      path: '/experience/$scene'
      fullPath: '/experience/$scene'
      preLoaderRoute: typeof ExperienceSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelfieRoute: SelfieRoute,
  WorldRoute: WorldRoute,
  ApiEnhanceRoute: ApiEnhanceRoute,
  ApiVideoRoute: ApiVideoRoute,
  ExperienceSceneRoute: ExperienceSceneRoute,
  RTokenRoute: RTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
